POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Concert é top",
    "details": "A concert is a live music",
    "maximumAttendees": 100
}

###

POST http://localhost:3333/events/d423d746-0cfe-4655-bf35-96485c0b1b4d/attendees
Content-Type: application/json


{
    "name": "Peter branch",
    "email": "peter@gmail.com"
}