POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo evento",
    "details": "Evento aleatorio",
    "maximumAttendees": 2
}

###

POST http://localhost:3333/events/94a5d872-9e67-4a81-a594-6926ec0a91ef/attendees
Content-Type: application/json


{
    "name": "Peter3 branch",
    "email": "peter3@gmail.com"
}



###

GET http://localhost:3333/events/94a5d872-9e67-4a81-a594-6926ec0a91ef


###

GET http://localhost:3333/attendees/4/badge


###


GET http://localhost:3333/attendees/4/check-in



###


GET http://localhost:3333/events/94a5d872-9e67-4a81-a594-6926ec0a91ef/attendees?query=Peter